import fs from "node:fs";
import path from "node:path";
import { stableJson } from "./io.mjs";

function nixString(value) {
  return JSON.stringify(value);
}

function nixAttrName(name) {
  return /^[A-Za-z_][A-Za-z0-9_'-]*$/.test(name) ? name : nixString(name);
}

function toNix(value, indent = "") {
  const nextIndent = `${indent}  `;
  if (value === null) {
    return "null";
  }
  if (typeof value === "string") {
    return nixString(value);
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[ ]";
    }
    return `[\n${value.map((item) => `${nextIndent}${toNix(item, nextIndent)}`).join("\n")}\n${indent}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) {
      return "{ }";
    }
    return `{\n${entries
      .map(([key, item]) => `${nextIndent}${nixAttrName(key)} = ${toNix(item, nextIndent)};`)
      .join("\n")}\n${indent}}`;
  }
  throw new Error(`Unsupported Nix value: ${value}`);
}

function renderLock(lock) {
  return `# Generated by nix/scripts/update-openclaw-runtime-plugin-locks.mjs. Do not edit manually.\n${toNix(lock)}\n`;
}

function renderDefault(locks) {
  const entries = locks
    .map((lock) => `  ${nixAttrName(lock.id)} = import ./${lock.attrName}.nix;`)
    .join("\n");
  return `# Generated by nix/scripts/update-openclaw-runtime-plugin-locks.mjs. Do not edit manually.\n{\n${entries}\n}\n`;
}

export { nixString, toNix };

export function createGeneratedOutput({ repoRoot, outputDir, packageLocks }) {
  const defaultOutputPath = path.join(outputDir, "default.nix");
  const reportOutputPath = path.join(outputDir, "report.json");
  function desiredGeneratedFiles(locks, report) {
    return new Map([
      ...locks.map((lock) => [
        path.join(outputDir, `${lock.attrName}.nix`),
        renderLock(lock),
      ]),
      ...[...packageLocks.generatedFiles].map(([file, text]) => [path.join(outputDir, file), text]),
      [defaultOutputPath, renderDefault(locks)],
      [reportOutputPath, stableJson(report)],
    ]);
  }

  function existingGeneratedFiles() {
    if (!fs.existsSync(outputDir)) {
      return [];
    }
    return fs
      .readdirSync(outputDir)
      .filter((entry) => entry === "report.json" || entry.endsWith(".nix") || entry.endsWith(".package-lock.json"))
      .map((entry) => path.join(outputDir, entry));
  }

  function checkGeneratedFiles(desiredFiles) {
    const staleFiles = existingGeneratedFiles().filter((file) => !desiredFiles.has(file));
    const changedFiles = [];

    for (const [file, content] of desiredFiles) {
      if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content) {
        changedFiles.push(file);
      }
    }

    if (staleFiles.length === 0 && changedFiles.length === 0) {
      return;
    }

    for (const file of changedFiles) {
      console.error(`would update ${path.relative(repoRoot, file)}`);
    }
    for (const file of staleFiles) {
      console.error(`would remove ${path.relative(repoRoot, file)}`);
    }
    process.exit(1);
  }

  return { desiredGeneratedFiles, existingGeneratedFiles, checkGeneratedFiles };
}
