#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source_file="$repo_root/nix/sources/openclaw-source.nix"
app_file="$repo_root/nix/packages/openclaw-app.nix"

mode="${1:-check}"
case "$mode" in
  check | publish) ;;
  *)
    echo "Usage: scripts/publish-release-tag.sh [check|publish]" >&2
    exit 2
    ;;
esac

log() {
  printf '>> %s\n' "$*" >&2
}

emit_output() {
  local key="$1"
  local value="$2"

  printf '%s=%s\n' "$key" "$value"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    printf '%s=%s\n' "$key" "$value" >>"$GITHUB_OUTPUT"
  fi
}

summary() {
  local message="$1"

  if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
    printf '%s\n' "$message" >>"$GITHUB_STEP_SUMMARY"
  fi
}

require_cmds() {
  local cmd
  for cmd in "$@"; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
      echo "$cmd is required but not installed." >&2
      exit 1
    fi
  done
}

field() {
  local file="$1"
  local key="$2"

  awk -F'"' -v key="$key" '$0 ~ key" =" { print $2; exit }' "$file"
}

require_clean_value() {
  local name="$1"
  local value="$2"

  if [[ -z "$value" ]]; then
    echo "Missing required release field: $name" >&2
    exit 1
  fi
}

write_release_notes() {
  local notes_file="$1"
  local tag="$2"
  local source_version="$3"
  local source_rev="$4"
  local head_sha="$5"
  local ci_run_url="$6"
  local upstream_release_url="https://github.com/openclaw/openclaw/releases/tag/${tag}"

  {
    printf 'nix-openclaw package state for OpenClaw `%s`.\n' "$tag"
    printf '\n'
    printf 'Upstream OpenClaw release: %s\n' "$upstream_release_url"
    printf '\n'
    printf 'Install with Nix:\n'
    printf '\n'
    printf '```bash\n'
    printf 'nix run github:openclaw/nix-openclaw/%s#openclaw\n' "$tag"
    printf '```\n'
    printf '\n'
    printf '%s\n' 'Pins:'
    printf '%s\n' "- OpenClaw source: [\`$tag\`]($upstream_release_url) (\`$source_rev\`)"
    printf '%s\n' "- macOS app artifact: [\`OpenClaw-${source_version}.zip\`]($upstream_release_url)"
    printf '%s\n' "- nix-openclaw commit: \`$head_sha\`"
    if [[ -n "$ci_run_url" ]]; then
      printf '%s\n' "- CI proof: $ci_run_url"
    else
      printf '%s\n' '- CI proof: green `CI` on `main` before tag creation'
    fi
    printf '\n'
    printf 'This release is generated by nix-openclaw automation. It is not a separate upstream OpenClaw release.\n'
  } >"$notes_file"
}

sync_github_release() {
  local tag="$1"
  local target_sha="$2"
  local source_version="$3"
  local source_rev="$4"
  local ci_run_url="$5"
  local notes_file
  local current_body
  local desired_body

  notes_file=$(mktemp)
  trap 'rm -f "$notes_file"' RETURN
  write_release_notes "$notes_file" "$tag" "$source_version" "$source_rev" "$target_sha" "$ci_run_url"

  if current_body=$(gh release view "$tag" --repo "$repo" --json body --jq .body 2>/dev/null); then
    desired_body=$(<"$notes_file")
    if [[ "$current_body" == "$desired_body" ]]; then
      log "GitHub Release $tag already up to date"
      return 0
    fi

    log "Updating GitHub Release $tag"
    gh release edit "$tag" \
      --repo "$repo" \
      --target "$target_sha" \
      --title "nix-openclaw $tag" \
      --notes-file "$notes_file"
  else
    log "Creating GitHub Release $tag"
    gh release create "$tag" \
      --repo "$repo" \
      --target "$target_sha" \
      --title "nix-openclaw $tag" \
      --notes-file "$notes_file"
  fi
}

require_cmds awk git

source_tag=$(field "$source_file" "releaseTag")
source_version=$(field "$source_file" "releaseVersion")
source_rev=$(field "$source_file" "rev")
app_version=$(field "$app_file" "version")
app_url=$(field "$app_file" "url")

require_clean_value "openclaw-source.releaseTag" "$source_tag"
require_clean_value "openclaw-source.releaseVersion" "$source_version"
require_clean_value "openclaw-source.rev" "$source_rev"
require_clean_value "openclaw-app.version" "$app_version"
require_clean_value "openclaw-app.url" "$app_url"

tag="$source_tag"
eligible=true
skip_reason=""

if [[ "$source_tag" != "v${source_version}" ]]; then
  eligible=false
  skip_reason="source-tag-version-mismatch"
elif [[ "$app_version" != "$source_version" ]]; then
  eligible=false
  skip_reason="source-app-version-mismatch"
elif [[ "$app_url" != *"/releases/download/${source_tag}/OpenClaw-${source_version}.zip" ]]; then
  eligible=false
  skip_reason="app-artifact-url-mismatch"
fi

emit_output "tag" "$tag"
emit_output "source_version" "$source_version"
emit_output "source_rev" "$source_rev"
emit_output "app_version" "$app_version"
emit_output "eligible" "$eligible"
emit_output "skip_reason" "$skip_reason"

if [[ "$eligible" != "true" ]]; then
  log "Skipping mirrored release tag $tag: $skip_reason"
  summary "### Mirrored release tag skipped

- Tag: \`$tag\`
- Reason: \`$skip_reason\`
- Source version: \`$source_version\`
- App version: \`$app_version\`
"
  exit 0
fi

if [[ "$mode" == "check" ]]; then
  log "Mirrored release tag $tag is eligible"
  exit 0
fi

require_cmds gh

repo="${GITHUB_REPOSITORY:-openclaw/nix-openclaw}"
head_sha=$(git rev-parse HEAD)

git fetch --force origin main 'refs/tags/*:refs/tags/*' >/dev/null
main_sha=$(git rev-parse origin/main)
if [[ "$head_sha" != "$main_sha" ]]; then
  log "Skipping $tag: checked-out commit $head_sha is not current origin/main $main_sha"
  summary "### Mirrored release tag skipped

- Tag: \`$tag\`
- Reason: checked-out commit is no longer current \`origin/main\`
- Checked-out commit: \`$head_sha\`
- Current main: \`$main_sha\`
"
  exit 0
fi

upstream_status=$(gh release view "$tag" --repo openclaw/openclaw --json isDraft,isPrerelease --jq '[.isDraft, .isPrerelease] | @tsv')
upstream_draft=${upstream_status%%$'\t'*}
upstream_prerelease=${upstream_status##*$'\t'}
if [[ "$upstream_draft" == "true" || "$upstream_prerelease" == "true" ]]; then
  echo "Refusing to publish mirrored tag for non-stable upstream release: $tag" >&2
  exit 1
fi

app_asset_count=$(gh release view "$tag" --repo openclaw/openclaw --json assets --jq "[.assets[] | select(.name == \"OpenClaw-${source_version}.zip\")] | length")
if [[ "$app_asset_count" != "1" ]]; then
  echo "Refusing to publish mirrored tag $tag: upstream release does not expose OpenClaw-${source_version}.zip" >&2
  exit 1
fi

if git show-ref --verify --quiet "refs/tags/${tag}"; then
  tag_sha=$(git rev-parse "refs/tags/${tag}^{commit}")
  if [[ "$tag_sha" != "$head_sha" ]]; then
    log "Tag $tag already exists at $tag_sha; not moving it to $head_sha"
    sync_github_release "$tag" "$tag_sha" "$source_version" "$source_rev" ""
    summary "### Mirrored release tag already exists

- Tag: \`$tag\`
- Existing target: \`$tag_sha\`
- Current main: \`$head_sha\`
- Release: synced for existing tag target
- Action: no retag; automation treats public tags as immutable
"
    exit 0
  fi
  log "Tag $tag already exists at current main"
else
  log "Creating annotated tag $tag at $head_sha"
  git tag -a "$tag" \
    -m "nix-openclaw $tag" \
    -m "Upstream OpenClaw release: https://github.com/openclaw/openclaw/releases/tag/${tag}"
  git push origin "refs/tags/${tag}"
fi

sync_github_release "$tag" "$head_sha" "$source_version" "$source_rev" "${CI_RUN_URL:-}"

summary "### Mirrored release tag published

- Tag: \`$tag\`
- Target: \`$head_sha\`
- OpenClaw source: \`$tag\` (\`$source_rev\`)
- macOS app artifact: \`OpenClaw-${source_version}.zip\`
- Release: synced
"
